name: flutter_live
version: 0.0.1
description: Live streaming demo by Flutter+SRS.
homepage: https://github.com/ossrs/flutter_live

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
